// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4La3k63wZ8gIsICt56j3uBZKHTCbxZkU',
    appId: '1:800833462997:web:69e796359fd5ae12cc385c',
    messagingSenderId: '800833462997',
    projectId: 'pi-iii-d8570',
    authDomain: 'pi-iii-d8570.firebaseapp.com',
    storageBucket: 'pi-iii-d8570.firebasestorage.app',
    measurementId: 'G-WVK7HP9CHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNgY4iW8UDHH2LT3dR8anoWzHssQF6D8',
    appId: '1:800833462997:android:43d83263b4ec61e5cc385c',
    messagingSenderId: '800833462997',
    projectId: 'pi-iii-d8570',
    storageBucket: 'pi-iii-d8570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjznkfIdpayTRNZ22IU3NYnCxBr-zc4Kg',
    appId: '1:800833462997:ios:7ea5d8100c508f06cc385c',
    messagingSenderId: '800833462997',
    projectId: 'pi-iii-d8570',
    storageBucket: 'pi-iii-d8570.firebasestorage.app',
    iosBundleId: 'com.example.investUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjznkfIdpayTRNZ22IU3NYnCxBr-zc4Kg',
    appId: '1:800833462997:ios:7ea5d8100c508f06cc385c',
    messagingSenderId: '800833462997',
    projectId: 'pi-iii-d8570',
    storageBucket: 'pi-iii-d8570.firebasestorage.app',
    iosBundleId: 'com.example.investUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4La3k63wZ8gIsICt56j3uBZKHTCbxZkU',
    appId: '1:800833462997:web:46012c5ac035773bcc385c',
    messagingSenderId: '800833462997',
    projectId: 'pi-iii-d8570',
    authDomain: 'pi-iii-d8570.firebaseapp.com',
    storageBucket: 'pi-iii-d8570.firebasestorage.app',
    measurementId: 'G-DQPPDRH66L',
  );
}
